FROM python:3.11-slim

ENV PYTHONUNBUFFERED=1
ENV NLTK_DATA=/app/nltk_data

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    git \
    libgl1 \
    libglib2.0-0 \
    libomp-dev \
    curl \
    unzip \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install --upgrade pip \
 && pip install --no-cache-dir -r requirements.txt

# Копируем скрипты загрузки
COPY scripts/ /app/scripts/

# Скачиваем NLTK данные и модели (все зависимости уже установлены)
RUN python /app/scripts/download_nltk.py && \
    python /app/scripts/download_models.py && \
    rm -rf /app/scripts   # скрипты больше не нужны, освобождаем место

# Копируем код приложения
COPY config.py .
COPY service.py .
COPY internal/ ./internal/

EXPOSE 9090

CMD ["python", "service.py"]